# Scikit-learn

Scikit-learn or sklearn is the most popular Python package for machine learning. The project started as scikits.learn, a Google Summer of Code project in 2007 by David Cournapeau. It was orginially developed as separate SciPy Toolkit - a third-party extension to Scipy and hence then name Scikit. The original codebase was later rewritten by other developers and in 2010 Fabian Pedregosa, Gael Varoquaux, Alexandre
Gramfort and Vincent Michel, all from FIRCA - French Institute for Research in Computer Science and Automation - took this project to the next level and made the first public release in February 2010.

Scikit-learn has a slew of machine learning models and provides functions that are needed for a data science workflow. These includes tools for data preprocessing, model selection, model fitting and evaluation among many other utilities. It features various classification, regression, clustering and dimensionality reduction algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN. Scikit-learn makes working with complicated machine learning workflows for small and medium datasets a breeze with its powerful API. It is built upon NumPy, SciPy and matplotlib libraries, which enable efficient in-core numerical and scientific computation.

## Installation

In [1]:
# # Scikit-learn is shipped with Ananconda distribution.
# # For new installation, use either pip or conda.
# # Using pip
# pip install scikit-learn
# # Using conda
# conda install scikit-learn

## Import Package

Scikit-learn relies heavily on object-oriented programming principles. It implements machine learning algorithms as classes and objects are created from these classes.

In [2]:
# To import whole library
import sklearn

# To import particular classes or methods of class objects
# loading dataset
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

# data preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest

# selecting the estimator
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import k_means

# selecting the metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [3]:
# Import required libraries - data manipulation
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Load Data

In [9]:
# Get data
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing
boston_data = fetch_california_housing()
print(boston_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [10]:
type(boston_data)

sklearn.utils._bunch.Bunch

In [11]:
boston_data.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [12]:
# Define feature and target
X = boston_data['data'] # Feature
y = boston_data['target'] # Label

In [14]:
# Print Description
print(boston_data['DESCR'])

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

The prices of the house indicated by the variable MEDV is the target variable and the remaining are the feature variables based on which we will predict the value of a house.

In [15]:
# Subsume into a dataframe
boston = pd.DataFrame(boston_data['data'], columns=boston_data['feature_names'])
boston.head(507)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
502,1.3785,47.0,4.310345,0.962382,843.0,2.642633,37.85,-122.27
503,2.9018,52.0,4.621212,1.098485,281.0,2.128788,37.85,-122.28
504,1.7300,44.0,5.024510,0.970588,506.0,2.480392,37.85,-122.28
505,2.2625,48.0,4.427039,1.038627,1054.0,2.261803,37.85,-122.28
506,2.2106,35.0,4.521739,1.012077,1017.0,2.456522,37.84,-122.29

In [16]:
# Check the dimension
boston.shape

(20640, 8)

In [17]:
# Verify missing values on features
boston.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [18]:
# Verify missing values on labels
pd.DataFrame(y).isnull().sum()

0    0
dtype: int64

In [19]:
# Data Exploration - Summary Statistics
boston.describe().T

,count,mean,std,min,25%,50%,75%,max
MedInc,20640.0,3.870671,1.899822,0.499900,2.563400,3.534800,4.743250,15.000100
HouseAge,20640.0,28.639486,12.585558,1.000000,18.000000,29.000000,37.000000,52.000000
AveRooms,20640.0,5.429000,2.474173,0.846154,4.440716,5.229129,6.052381,141.909091
AveBedrms,20640.0,1.096675,0.473911,0.333333,1.006079,1.048780,1.099526,34.066667
Population,20640.0,1425.476744,1132.462122,3.000000,787.000000,1166.000000,1725.000000,35682.000000
AveOccup,20640.0,3.070655,10.386050,0.692308,2.429741,2.818116,3.282261,1243.333333
Latitude,20640.0,35.631861,2.135952,32.540000,33.930000,34.260000,37.710000,41.950000
Longitude,20640.0,-119.569704,2.003532,-124.350000,-121.800000,-118.490000,-118.010000,-114.310000

## Estimator API

Machine learning algorithms and models are referred as estimators. There are three different types of estimators transformers, classifiers and regressors .
Following are the basic API structure.
1. Choose a class of model
2. Choose model hyperparameters
3. Arrange the data
4. Fit the model
5. Apply the model: 
a) supervised learning, use predict() method to predict the labels for unknown data.
b) unsupervised learning, use predict() or transform() to infer properties of the data.

### Transformers

Transformers are models that process and transform a data set. These transformers are quite useful as rarely the data is in a form where we can feed them directly to a machine learning model. A typical pipeline consists of a pre-processing step that transforms or imputes the data, and a final predictor that predicts target values and the effectiveness of models improve a lot when the features have similar scales. All transformers have the same interface:

- `fit(X)`: train or fit the object to the feature matrix \( X \).
- `transform(X)`: applies the transformation on \( X \) using any parameters learned.
- `fit_transform(X)`: applies both `fit(X)` and then `transform(X)`.

For example, `StandardScaler` transform (scales) each feature to have zero mean and unit variance. The transformed feature $xt_i$ is equal to
$$
xt_i = \frac{x_i - \mu_i}{\sigma_i}
$$

We'll use pandas to summarize the results of deploying the `StandardScaler` on the boston dataset.

In [20]:
from sklearn.preprocessing import StandardScaler

# create and fit scaler
scaler = StandardScaler()
scaler.fit(X)

# scale data set
Xt = scaler.transform(X)

# create data frame with results
stats = np.vstack((X.mean(axis=0), X.var(axis=0), Xt.mean(axis=0), Xt.var(axis=0))).T
feature_names = boston_data['feature_names']
columns = ['unscaled mean', 'unscaled variance', 'scaled mean', 'scaled variance']

df = pd.DataFrame(stats, index=feature_names, columns=columns)

In [21]:
df

            unscaled mean  unscaled variance   scaled mean  scaled variance
MedInc           3.870671       3.609148e+00  6.609700e-17              1.0
HouseAge        28.639486       1.583886e+02  5.508083e-18              1.0
AveRooms         5.429000       6.121236e+00  6.609700e-17              1.0
AveBedrms        1.096675       2.245806e-01 -1.060306e-16              1.0
Population    1425.476744       1.282408e+06 -1.101617e-17              1.0
AveOccup         3.070655       1.078648e+02  3.442552e-18              1.0
Latitude        35.631861       4.562072e+00 -1.079584e-15              1.0
Longitude     -119.569704       4.013945e+00 -8.526513e-15              1.0

Feature scaling is one of the most critical steps during the pre-processing of data before creating actual machine learning model. The idea of feature scaling is to make sure that features are on a similar scale. Scaling can make a big difference between a weak machine learning model and a better one. Further, scaling enables faster convergence or calculation of cost functions in gradient descent. The most common feature scaling techniques are Normalization and Standardization.

For list of transformers in Scikit-learn, refer transformers and to compare the effect of different scalers on data on outliers.

In [22]:
from sklearn import preprocessing

### MinMaxScaler

Scaling or rescaling is the most common preprocessing task in machine learning. The algorithms will assume all features are on the same scale, *typically 0 to 1 or -1 to 1*. `MinMaxScaler` is one of the simplest scaling methods which is also commonly referred to as normalization.  

Min-max scaling uses the minimum and maximum values of a feature to rescale values to within a range.

Min-max is calculated as  

$$
x_{\text{scaled}} = \frac{x_i - \min(x)}{\max(x) - \min(x)}
$$

where $x$ is the feature vector, $x_i$ is an individual element of feature $x$, and $x_{\text{scaled}}$ is the rescaled element.  

The two options to rescale a feature are:  
- `fit` to calculate the minimum and maximum values of the feature, then use `transform` to rescale the feature.  
- `fit_transform` to do both operations at once.  

While there is no mathematical difference between the two options, sometimes we benefit from keeping these operations separate as it allows us to apply the same transformation to different sets of the data.

In [23]:
Xs = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
Xs

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [24]:
# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

# Scale or Transform the feature
scaled_X = minmax_scale.fit_transform(Xs)
scaled_X

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### StandardScaler

also depends on the learning algorithm. For example, principal component analysis often works better using standardization, while normalization is often preferred for neural networks. As a rule of thumb, always default to standardization unless you have a specific reason to adopt to other scaling methods.

Standardization is *z-scoring* of the features where we rescale the features to be approximately standard normally distributed. The data is transformed to have a mean, \( x^* \) of 0 and a standard deviation, \( \sigma \) of 1.

`StandardScaler` is calculated as  

$$
x_{\text{scaled}} = \frac{x_i - \bar{x}}{\sigma}
$$

where $x$ is the feature vector, $x_i$ is an individual element of feature $x$, and $x_{\text{scaled}}$ is the rescaled element.

In [25]:
# Create feature
Xs = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
Xs

array([[-1000.1],
       [ -200.2],
       [  500.5],
       [  600.6],
       [ 9000.9]])

In [26]:
# Create scaler
scaler = preprocessing.StandardScaler()

# Transform the feature
scaled_X = scaler.fit_transform(Xs)

scaled_X

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [27]:
# Mean and Standard deviation of scaled feature
scaled_X. mean(), scaled_X.std()

(4.4408920985006264e-17, 1.0)

### RobustScaler

If the data has significant outliers, it can significantly impact our standardization by affecting the feature’s mean and variance. In such scenarios, we scale features using statistics that are robust to outliers. We do this by removing the median and scaling the data according to the quantile range (defaults to IQR: Interquartile Range). The IQR is the range between the 1st quartile (25th quantile) and the 3rd quartile (75th quantile).

`RobustScaler` is calculated as  

$$
x_{\text{scaled}} = \frac{x_i - Q_1(x)}{Q_3(x) - Q_1(x)}
$$

where $x$ is the feature vector, $x_i$ is an individual element of feature $x$, $Q_1(x)$, $Q_3(x)$ is the first and third quartile of feature and $x_{\text{scaled}}$ is the rescaled element.

In [28]:
# Create scaler
robust_scaler = preprocessing.RobustScaler()

# Transform feature
robust_scaler.fit_transform(Xs)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

### Normalizer

`Normalizer` rescales the feature values of observations to have unit norm (a total length of one). This is different from min-max scaler which is also commonly referred as normalization. The key difference is that normalizer works on the rows, not the columns. Meaning, we rescale across individual observations.

By default, **L2 normalization** is applied to each observation so that the values in a row have a unit norm. Unit norm with **L2** means that if each element were squared and summed, the total would be equal to one. Alternatively, **L1** can be applied instead of **L2** normalization.

The three norm options

1. **L1: Manhattan norm (taxicab norm)**

   - **Formula**  
     $$
     \|x\|_1 = \sum_{i=1}^{n} |x_i|
     $$
   - **Normalized form (definition 1)**  
     $$
     x_i^{\text{normed}} = \frac{x_i}{\|x\|_1}
     $$
   - **Normalized form (definition 2)**  
     $$
     x_i^{\text{normed}} = \frac{x_i}{\sum(x)}
     $$

2. **L2: Euclidean norm (default)**

   - **Formula**  
     $$
     \|x\|_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}
     $$
   - **Normalized form (definition 1)**  
     $$
     x_i^{\text{normed}} = \frac{x_i}{\|x\|_2}
     $$
   - **Normalized form (definition 2)**  
     $$
     x_i^{\text{normed}} = \frac{x_i}{\sqrt{\sum (x_i^2)}}
     $$

3. **Max norm (rescaled by the maximum of absolute values)**

   - **Formula for normalization**  
     $$
     x_i^{\text{normed}} = \frac{x_i}{\max\bigl(|x_1|, |x_2|, \dots, |x_n|\bigr)}
     $$
x_2|, \dots, |x_n|\bigr)}
     \]
\lvert x_n\rvert\right)}
     \]
d}} = \frac{x_i}{\max(X)}
  \]
\frac{x_i}{\max(X)}
    \]
i}{max(X)}

Normalizer is often used when there are many equivalent features such as text classification when every word or n-word group i a feature.

In [29]:
# Create feature matrix
Xs = np.array([[0.5, 0.5], [1.1, 3.4], [1.5, 20.2], [1.63, 34.4], [10.9, 3.3]])
Xs

array([[ 0.5 ,  0.5 ],
       [ 1.1 ,  3.4 ],
       [ 1.5 , 20.2 ],
       [ 1.63, 34.4 ],
       [10.9 ,  3.3 ]])

In [30]:
# Transform feature with l1 norm
preprocessing.Normalizer(norm="l1").fit_transform(Xs)

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [31]:
# Transform feature with l2 norm
preprocessing.Normalizer(norm="l2").fit_transform(Xs)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [32]:
# Transform feature with max norm
preprocessing.Normalizer(norm="max").fit_transform(Xs)

array([[1.        , 1.        ],
       [0.32352941, 1.        ],
       [0.07425743, 1.        ],
       [0.04738372, 1.        ],
       [1.        , 0.30275229]])

### When to do scaling?
If scaling is required, do we need to do it? Do we need to do it on

- a)	the entire dataset or
- b)	both the train and test datasets separately or
- c)	transform the training dataset and apply the same transformation on the test dataset?
 
- `Scenario 1`

scaled_dataset = (dataset - mean_dataset) / stdev_dataset train, test = split (scaled_dataset
- `
 Scenari`o 2

train, test = split (dataset)

scaled_train = (train - mean_train) / stdev_train scaled_test = (test - mean_test) / stdev
- `_test
 Sc`enario 3

scaled_train = (train - mean_train) / stdev_train scaled_test = (test - mean_train) / stdv_train

 Data Leakage is when information from outside the training dataset is used to create the model. This additional information can allow the model to learn or know something that it otherwise would not know and in turn invalidate the estimated performance of the mode being constructed.

### Predictors

Predictors are models that make predictions and the two main methods are

- fit(X, y) : train the object to the feature matrix X and label vector y.
- predict(X) : makes predictions on the passed (new) data set X.

In [33]:
from sklearn.linear_model import LinearRegression, Lasso

# create model and train/fit 
model = LinearRegression() 
model.fit(X, y) # training

# predict label values on X
y_pred = model.predict(X) # predicting

print(y_pred[:10])
print(f'R^2: {model.score(X, y):0.4}')

[4.13164983 3.97660644 3.67657094 3.2415985  2.41358744 2.67527702
 2.39539429 2.24668752 1.79162667 2.42832807]
R^2: 0.6062

In [34]:
np.around(model.coef_,1)

array([ 0.4,  0. , -0.1,  0.6, -0. , -0. , -0.4, -0.4])

What if we wanted to use a more complicated model?

In [35]:
from sklearn.ensemble import GradientBoostingRegressor

# create model and train/fit
model = GradientBoostingRegressor() 
model.fit(X, y)

# predict label values on X
y_pred = model.predict(X)

print(y_pred[:10])
print(f'R-Square: {model.score(X, y):0.4}')

[4.26432728 3.87864519 3.92074556 3.3034389  2.61281416 2.71898112
 2.37711881 2.48217063 1.90254137 2.48427233]
R-Square: 0.8033

### Pipelines

Transformers and estimators can be combined together into a single unifying object: a **Pipeline**. The pipeline offers the same API as a regular estimator: it can be fitted and used for prediction with fit and predict.

We can apply the transformations explicitly as above by creating intermediate variables of the transformed data. The other approach is to use Pipelines which can be used to chain multiple estimators into one. Pipelines are made with the  Pipeline class which an estimator object that holds a series of transformers with a final estimator. It is built using a list of  (key, value) pairs, where  key is a string containing the user defined name of the step and  value  is an estimator object.

In [36]:
# from sklearn.preprocessing import PolynomialFeatures 
# poly_features = PolynomialFeatures(degree=2)

Pipeline is sequential, whereas Feature Union is parallel.

In [37]:
from sklearn.pipeline import Pipeline

# list of tuples
pipe = Pipeline([('scaler', StandardScaler()), ('regressor', LinearRegression())])

In [38]:
pipe.named_steps

{'scaler': StandardScaler(), 'regressor': LinearRegression()}

As  Pipeline objects are estimators, the standard methods such as  fit(X, y) ,  predict(X) and  transform(X) applies to it as well. For the above constructed pipeline, when calling  pipe.fit(X, y) , the following process occurs:

Xt = scaler.fit_transform(X)  
LinearRegression().fit(Xt)

When calling  pipe.predict(X, y) , the data set  X will flow through the transformers and be used to make predictions with the predictor in the last stage.

Xt = scaler.transform(X)  
y_pred = LinearRegression().predict(Xt)

 
When encapsulating the entire workflow through a Pipeline object, we avoid manually calling the fitting, transformations, and predictions steps.

In [39]:
# fit/train model
pipe.fit(X, y)

# predict labels
y_pred = pipe.predict(X)

print(y_pred[:10])
print(f'R^2: {pipe.score(X, y):0.4}')

[4.13164983 3.97660644 3.67657094 3.2415985  2.41358744 2.67527702
 2.39539429 2.24668752 1.79162667 2.42832807]
R^2: 0.6062

### Feature Union

In some machine learning workflow, the data may require different transformation processes for certain features. The dataset may contain numerical, categorical, and text data. Each of these types may require different transformations and a convenient way to combine the results of these transformation. This is achieved with  FeatureUnion.

While the  Pipeline  objects arrange estimators in a series,  FeatureUnion objects arrange transformers in parallel. A  FeatureUnion object combines the output of the each of the transformers in parallel to generate one output matrix. Similar to Pipeline, FeatureUnion is built using a list of  (key, value) pairs.

In [40]:
from sklearn.pipeline import FeatureUnion
from sklearn.decomposition import PCA
from sklearn.feature_selection import f_regression, SelectKBest

#Pipeline([]) -- is the list of tuples

pca_pipe = Pipeline([('scaler', StandardScaler()), ('dim_red', PCA(n_components=4))])
union = FeatureUnion([('pca_pipe', pca_pipe), ('selector', SelectKBest(f_regression, k=2))])

pipe = Pipeline([('union', union), ('regressor', LinearRegression())]) # predictor is the last step
pipe.fit(X, y)

print(f'Number of features in the original dataset: {X.shape[-1]}') 
print(f'Number of features in the new dataset: {union.transform(X).shape[-1]}') 
print(f'R-Square: {pipe.score(X, y):0.4}')

Number of features in the original dataset: 8
Number of features in the new dataset: 6
R-Square: 0.5288

### Custom Estimators

Scikit-learn provides dozens of machine learning models and transformers. However, our workflow sometimes requires us to specify the models or transformations; and such models or transformations should have the fit, and either predict or transform methods that are in compliance with scikit-learn so that we can leverage its functionalities such as Pipeline, GridSearchCV classes and such other features.

This is achieved with custom estimators. Scikit-learn has a base class called  BaseEstimator that all estimators inherit and these models inherit additional classes such as  RegressorMixin, ClassifierMixin, and TransformerMixin. We can thus customize our models by inheriting these classes that are in compliance with scikit-learn.

### Custom Transformers

Transformers are estimators which implement a  transform method. Regressors are estimators that implement a  predict method while classifiers implement  predict method inaddition to the probability output of the predictions using the  predict_proba method.

Note: Refer Machine Learning assignments and solutions for implementation of Custom Estimators and Transformers.

## References

- Jake VanderPlas (2017), Python Data Science Handbook