In [1]:
# Import data manipulation libraries
import numpy as np
import pandas as pd
        
# Import yahoo finance library
import yfinance as yf

# Import cufflinks for visualization
import cufflinks as cf
cf.set_config_file(offline=True, theme='pearl')

# Machine info & package version
from watermark import watermark
%load_ext watermark
%watermark -a "Sun Yufei" -u -d -v -m -iv

# Ignore warnings - optional
import warnings
warnings.filterwarnings('ignore')

Author: Sun Yufei

Last updated: 2025-03-09

Python implementation: CPython
Python version       : 3.9.18
IPython version      : 8.15.0

Compiler    : MSC v.1916 64 bit (AMD64)
OS          : Windows
Release     : 10
Machine     : AMD64
Processor   : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
CPU cores   : 8
Architecture: 64bit

yfinance : 0.2.54
numpy    : 1.23.5
watermark: 2.5.0
cufflinks: 0.17.3
pandas   : 2.0.0

# Data Retrieval

## Retrieving end-of-day data for single security

In [2]:
# Fetch the data by specifying the number of period
df1 = yf.download('SPY', period='5d', progress=False)

# Display the first five rows of the dataframe to check the results. 
df1

YF.download() has changed argument auto_adjust default to True

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date
2025-03-03  583.770020  597.340027  579.900024  596.179993   74249200
2025-03-04  576.859985  585.390015  572.250000  579.710022  109648200
2025-03-05  583.059998  584.880005  573.080017  576.690002   71230500
2025-03-06  572.710022  580.169983  570.119995  575.479980   80094900
2025-03-07  575.919983  577.390015  565.630005  570.900024   81042900

In [3]:
# Fetch data by specifying the the start and end dates
df2 = yf.download('SPY', start='2022-06-01', end='2022-06-30', progress=False)

# Display the first five rows of the dataframe to check the results. 
df2.head()

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2022-06-01  393.206665  399.590664  390.653060  398.563485  86585800
2022-06-02  400.694641  400.742629  390.758630  393.043436  79609600
2022-06-03  394.118622  397.478624  393.129822  395.904209  71874300
2022-06-06  395.318695  399.945876  394.128274  398.189088  57508900
2022-06-07  399.110596  399.571406  391.305787  391.776207  59272400

In [4]:
# Fetch data for year to date (YTD)
df3 = yf.download('SPY', period='ytd', progress=False)

# Display the last five rows of the dataframe to check the results. 
df3.tail()

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date
2025-03-03  583.770020  597.340027  579.900024  596.179993   74249200
2025-03-04  576.859985  585.390015  572.250000  579.710022  109648200
2025-03-05  583.059998  584.880005  573.080017  576.690002   71230500
2025-03-06  572.710022  580.169983  570.119995  575.479980   80094900
2025-03-07  575.919983  577.390015  565.630005  570.900024   81042900

## Retrieving data for multiple securities

In [5]:
# Specify stocks
# https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average
dow_stocks = ['UNH', 'GS', 'HD', 'AMGN', 'MCD']

# Fetch data for multiple stocks at once
df4 = yf.download(dow_stocks, period='ytd', progress=False)['Close']

df4.tail()

Ticker            AMGN          GS          HD         MCD         UNH
Date
2025-03-03  310.779999  605.260010  389.690002  304.290009  467.049988
2025-03-04  312.190002  581.140015  381.679993  305.769989  474.609985
2025-03-05  316.570007  593.070007  386.350006  307.450012  475.980011
2025-03-06  317.820007  567.669983  381.730011  310.369995  487.720001
2025-03-07  324.859985  559.669983  376.799988  321.290009  493.480011

## Retrieving multiple fields for multiple securities

In [6]:
dow_stocks

['UNH', 'GS', 'HD', 'AMGN', 'MCD']

In [7]:
# Fetch data for multiple fields using comprehension
ohlcv = {symbol: yf.download(symbol, period='1y', progress=False) for symbol in dow_stocks}

ohlcv

{'UNH': Price            Close        High         Low        Open   Volume
 Ticker             UNH         UNH         UNH         UNH      UNH
 Date
 2024-03-08  471.073181  478.664592  469.293925  472.812861  4672600
 2024-03-11  483.508087  484.654711  470.509767  471.498233  4410100
 2024-03-12  483.705780  486.601978  481.728848  482.499850  4153800
 2024-03-13  482.371338  490.279065  479.732121  487.827659  3669000
 2024-03-14  483.359833  484.031982  479.593780  483.083064  3378500
 ...                ...         ...         ...         ...      ...
 2025-03-03  467.049988  477.269989  465.209991  474.369995  5700200
 2025-03-04  474.609985  479.209991  466.459991  469.750000  5864100
 2025-03-05  475.980011  479.079987  471.010010  471.070007  3637100
 2025-03-06  487.720001  488.119995  472.000000  476.000000  4964000
 2025-03-07  493.480011  499.920013  483.369995  483.829987  5431800

 [250 rows x 5 columns],
 'GS': Price            Close        High         Low        Open   Volume
 Ticker              GS          GS          GS          GS       GS
 Date
 2024-03-08  378.637238  387.080973  378.363282  380.339702  1657200
 2024-03-11  377.825195  378.069799  373.187512  377.345781  1654200
 2024-03-12  379.801605  380.731113  375.496580  379.253695  1703900
 2024-03-13  383.842438  386.718984  379.801574  380.515829  2370600
 2024-03-14  380.222321  387.824634  377.130552  385.916710  3029500
 ...                ...         ...         ...         ...      ...
 2025-03-03  605.260010  628.780029  598.320007  622.400024  3152300
 2025-03-04  581.140015  600.000000  567.570007  595.979980  4061000
 2025-03-05  593.070007  597.119995  576.780029  582.090027  2600600
 2025-03-06  567.669983  586.710022  564.619995  580.590027  4332300
 2025-03-07  559.669983  568.169983  544.909973  568.169983  4069600

 [250 rows x 5 columns],
 'HD': Price            Close        High         Low        Open   Volume
 Ticker              HD          HD          HD          HD       HD
 Date
 2024-03-08  366.603546  369.814446  365.376134  368.223725  2162400
 2024-03-11  364.806580  366.240219  362.204471  364.845865  2833700
 2024-03-12  367.772003  369.107413  365.680488  365.778687  2843800
 2024-03-13  372.141602  375.794382  368.989615  369.235097  3761200
 2024-03-14  368.488831  373.329768  365.444872  371.169510  3877500
 ...                ...         ...         ...         ...      ...
 2025-03-03  389.690002  397.070007  386.470001  396.950012  3397600
 2025-03-04  381.679993  387.959991  378.899994  386.149994  4384800
 2025-03-05  386.350006  387.119995  378.010010  379.000000  2780300
 2025-03-06  381.730011  387.760010  380.730011  383.500000  4222000
 2025-03-07  376.799988  380.649994  368.899994  379.500000  4573900

 [250 rows x 5 columns],
 'AMGN': Price            Close        High         Low        Open   Volume
 Ticker            AMGN        AMGN        AMGN        AMGN     AMGN
 Date
 2024-03-08  265.652069  268.378943  263.963550  264.739873  2250800
 2024-03-11  267.214447  269.960748  264.914560  266.389615  1851000
 2024-03-12  268.359528  269.921887  266.030529  268.660355  1738700
 2024-03-13  267.825775  270.319758  267.068850  269.950994  1641000
 2024-03-14  263.507446  269.029130  262.449694  268.650652  2370500
 ...                ...         ...         ...         ...      ...
 2025-03-03  310.779999  312.480011  307.339996  307.339996  2970700
 2025-03-04  312.190002  319.820007  312.100006  316.529999  3820000
 2025-03-05  316.570007  318.940002  310.140015  310.630005  2629000
 2025-03-06  317.820007  318.679993  312.500000  316.420013  3076500
 2025-03-07  324.859985  328.190002  317.779999  318.950012  3944200

 [250 rows x 5 columns],
 'MCD': Price            Close        High         Low        Open   Volume
 Ticker             MCD         MCD         MCD         MCD      MCD
 Date
 2024-03-08  285.604309  286.512252  281.972628  283.153921  2481800
 2024-03-11  287.820465  288.435513  284.940491  285.213842  2893300
 2024-03-12  287.322479  289.323796  286.570771  288.659948  2233100
 2024-03-13  276.144379  286.502494  275.890572  285.321230  5441300
 2024-03-14  275.041199  275.812421  271.233768  275.714819  4659300
 ...                ...         ...         ...         ...      ...
 2025-03-03  304.290009  309.489990  302.429993  308.109985  4371300
 2025-03-04  305.769989  312.929993  304.589996  304.589996  3954500
 2025-03-05  307.450012  308.459991  303.369995  304.000000  2327500
 2025-03-06  310.369995  311.350006  304.380005  307.799988  2954900
 2025-03-07  321.290009  323.170013  310.350006  310.820007  7606700

 [250 rows x 5 columns]}

In [8]:
# Display GS stock data
ohlcv['GS'].head()

Price            Close        High         Low        Open   Volume
Ticker              GS          GS          GS          GS       GS
Date
2024-03-08  378.637238  387.080973  378.363282  380.339702  1657200
2024-03-11  377.825195  378.069799  373.187512  377.345781  1654200
2024-03-12  379.801605  380.731113  375.496580  379.253695  1703900
2024-03-13  383.842438  386.718984  379.801574  380.515829  2370600
2024-03-14  380.222321  387.824634  377.130552  385.916710  3029500

In [9]:
# Display GS adjusted close data
ohlcv['GS']['Close']

Ticker              GS
Date
2024-03-08  378.637238
2024-03-11  377.825195
2024-03-12  379.801605
2024-03-13  383.842438
2024-03-14  380.222321
...                ...
2025-03-03  605.260010
2025-03-04  581.140015
2025-03-05  593.070007
2025-03-06  567.669983
2025-03-07  559.669983

[250 rows x 1 columns]

## Retrieving intraday data

In [10]:
# Retrieve intraday data for last five days
df6 = yf.download('SPY', period='5d', interval='1m', progress=False)

# Display dataframe
df6

Price,Close,High,Low,Open,Volume
Ticker,SPY,SPY,SPY,SPY,SPY
Datetime,,,,,
2025-03-03 14:30:00+00:00,595.870972,596.179993,595.619995,596.179993,2006464
2025-03-03 14:31:00+00:00,596.625000,596.625000,595.840027,595.869995,206906
2025-03-03 14:32:00+00:00,597.059998,597.091309,596.619995,596.625000,250108
2025-03-03 14:33:00+00:00,596.700012,597.340027,596.650024,597.070007,237428
2025-03-03 14:34:00+00:00,596.869995,597.159912,596.650024,596.700012,206687
...,...,...,...,...,...
2025-03-07 20:55:00+00:00,576.640015,577.390015,576.570007,576.570007,916880
2025-03-07 20:56:00+00:00,576.409973,576.789978,576.140015,576.669983,391919
2025-03-07 20:57:00+00:00,576.440002,576.530029,576.210022,576.440002,394858
2025-03-07 20:58:00+00:00,576.440002,576.539978,576.229980,576.450012,359863
2025-03-07 20:59:00+00:00,575.859985,576.460022,575.719971,576.434998,1461890

## Retrieving option chain

We'll now retrieve option chain for SPY for March 2022 expiration from yahoo finance and filter the output to display the first seven columns.

In [12]:
# Get SPY option chain for Sept 30th expiration
# https://finance.yahoo.com/quote/SPY/options?date=1680220800
spy = yf.Ticker('SPY')
options = spy.option_chain('2025-03-11')
options

Options(calls=        contractSymbol             lastTradeDate  strike  lastPrice    bid
0   SPY250311C00560000 2025-03-07 20:45:41+00:00   560.0      18.00  16.47  \
1   SPY250311C00565000 2025-03-07 21:06:26+00:00   565.0      11.83  12.20
2   SPY250311C00570000 2025-03-07 21:14:26+00:00   570.0       8.32   8.42
3   SPY250311C00571000 2025-03-07 21:14:24+00:00   571.0       7.59   7.73
4   SPY250311C00572000 2025-03-07 21:14:27+00:00   572.0       7.00   7.07
5   SPY250311C00573000 2025-03-07 21:14:29+00:00   573.0       6.38   6.44
6   SPY250311C00574000 2025-03-07 21:09:33+00:00   574.0       5.88   5.84
7   SPY250311C00575000 2025-03-07 21:14:33+00:00   575.0       5.21   5.26
8   SPY250311C00576000 2025-03-07 21:14:49+00:00   576.0       4.71   4.71
9   SPY250311C00578000 2025-03-07 21:14:40+00:00   578.0       3.68   3.70
10  SPY250311C00579000 2025-03-07 21:14:41+00:00   579.0       3.23   3.25
11  SPY250311C00580000 2025-03-07 21:14:53+00:00   580.0       2.85   2.83
12  SPY250311C00581000 2025-03-07 21:14:36+00:00   581.0       2.40   2.43
13  SPY250311C00582000 2025-03-07 21:14:59+00:00   582.0       2.10   2.07
14  SPY250311C00583000 2025-03-07 21:14:46+00:00   583.0       1.74   1.74
15  SPY250311C00584000 2025-03-07 21:14:24+00:00   584.0       1.40   1.45
16  SPY250311C00585000 2025-03-07 21:14:57+00:00   585.0       1.20   1.18
17  SPY250311C00586000 2025-03-07 21:14:49+00:00   586.0       0.95   0.95
18  SPY250311C00587000 2025-03-07 21:13:39+00:00   587.0       0.75   0.75
19  SPY250311C00588000 2025-03-07 21:14:42+00:00   588.0       0.57   0.58
20  SPY250311C00589000 2025-03-07 21:14:47+00:00   589.0       0.45   0.44
21  SPY250311C00590000 2025-03-07 21:14:54+00:00   590.0       0.33   0.32
22  SPY250311C00591000 2025-03-07 21:14:58+00:00   591.0       0.25   0.24
23  SPY250311C00592000 2025-03-07 21:14:55+00:00   592.0       0.18   0.17
24  SPY250311C00593000 2025-03-07 21:14:38+00:00   593.0       0.12   0.12
25  SPY250311C00594000 2025-03-07 21:13:42+00:00   594.0       0.09   0.08
26  SPY250311C00595000 2025-03-07 21:12:05+00:00   595.0       0.06   0.05
27  SPY250311C00596000 2025-03-07 21:05:26+00:00   596.0       0.04   0.03
28  SPY250311C00597000 2025-03-07 21:00:23+00:00   597.0       0.03   0.02
29  SPY250311C00598000 2025-03-07 21:12:16+00:00   598.0       0.02   0.01
30  SPY250311C00599000 2025-03-07 21:11:24+00:00   599.0       0.01   0.01
31  SPY250311C00600000 2025-03-07 21:11:14+00:00   600.0       0.01   0.01
32  SPY250311C00601000 2025-03-07 21:02:42+00:00   601.0       0.01   0.01
33  SPY250311C00602000 2025-03-07 21:10:51+00:00   602.0       0.02   0.01
34  SPY250311C00603000 2025-03-07 21:13:04+00:00   603.0       0.01   0.00
35  SPY250311C00604000 2025-03-07 20:40:09+00:00   604.0       0.01   0.00
36  SPY250311C00605000 2025-03-07 19:58:31+00:00   605.0       0.01   0.00
37  SPY250311C00606000 2025-03-07 15:13:22+00:00   606.0       0.01   0.00
38  SPY250311C00607000 2025-03-07 19:45:44+00:00   607.0       0.02   0.00
39  SPY250311C00608000 2025-03-07 19:05:18+00:00   608.0       0.02   0.00
40  SPY250311C00609000 2025-03-07 17:21:10+00:00   609.0       0.01   0.00
41  SPY250311C00610000 2025-03-07 19:40:19+00:00   610.0       0.01   0.00
42  SPY250311C00611000 2025-03-07 18:51:14+00:00   611.0       0.01   0.00
43  SPY250311C00612000 2025-03-07 19:53:59+00:00   612.0       0.01   0.00
44  SPY250311C00613000 2025-03-07 20:09:53+00:00   613.0       0.01   0.00
45  SPY250311C00614000 2025-03-07 19:58:56+00:00   614.0       0.01   0.00
46  SPY250311C00615000 2025-03-07 19:58:56+00:00   615.0       0.01   0.00
47  SPY250311C00616000 2025-03-06 18:39:08+00:00   616.0       0.01   0.00
48  SPY250311C00617000 2025-03-05 21:04:01+00:00   617.0       0.01   0.00
49  SPY250311C00618000 2025-03-07 18:10:59+00:00   618.0       0.01   0.00
50  SPY250311C00619000 2025-03-07 18:08:17+00:00   619.0       0.01   0.00
51  SPY250311C00620000 2025-03-07 18:11:46+00:00   620.0       0.01   0.00
52  SPY250311C00625000 2025-03-06 18:59:01+00:00   625.0       0.03   0.00
53  SPY250311C00630000 2025-03-07 17:42:20+00:00   630.0       0.01   0.00
54  SPY250311C00635000 2025-03-07 17:34:21+00:00   635.0       0.01   0.00
55  SPY250311C00640000 2025-03-05 17:53:14+00:00   640.0       0.01   0.00
56  SPY250311C00645000 2025-03-05 17:00:27+00:00   645.0       0.02   0.00
57  SPY250311C00650000 2025-02-26 15:49:26+00:00   650.0       0.02   0.00
58  SPY250311C00680000 2025-02-26 15:20:12+00:00   680.0       0.01   0.00

      ask    change  percentChange   volume  openInterest  impliedVolatility
0   16.61  2.100000      13.207550    205.0            73           0.252205  \
1   12.32 -0.420000      -3.428572    638.0           195           0.247566
2    8.50 -0.980001     -10.537640   7880.0          2659           0.240852
3    7.81 -1.059999     -12.254330   4740.0          1754           0.239510
4    7.14 -1.060000     -13.151370   6698.0           909           0.237679
5    6.50 -1.270000     -16.601307   6718.0          1994           0.235970
6    5.89 -1.050000     -15.151511   7540.0           773           0.234139
7    5.31 -1.220000     -18.973558  12056.0          1211           0.232307
8    4.76 -1.230000     -20.707071   6706.0           927           0.230415
9    3.75 -1.330000     -26.546907   4381.0           769           0.226082
10   3.29 -1.330000     -29.166666   6427.0          1662           0.223519
11   2.86 -1.280000     -30.992740  14512.0          1412           0.220833
12   2.47 -1.320000     -35.483870   4117.0           787           0.218270
13   2.10 -1.290000     -38.053100   4992.0           780           0.214974
14   1.78 -1.290000     -42.574257   3812.0          1021           0.212532
15   1.48 -1.130000     -44.664032   4504.0          1083           0.209114
16   1.21 -1.210000     -50.207466   7811.0          1808           0.205330
17   0.98 -1.160000     -54.976295   4031.0           725           0.202156
18   0.77 -1.110000     -59.677420   3836.0          1106           0.197762
19   0.60 -1.050000     -64.814810   5930.0           926           0.194222
20   0.46 -0.930000     -67.391304   3863.0           615           0.190682
21   0.33 -0.850000     -72.033900   9864.0          3303           0.185311
22   0.25 -0.750000     -75.000000   3799.0          1140           0.183358
23   0.18 -0.620000     -77.500000   6224.0          1411           0.180184
24   0.13 -0.550000     -82.089550   3785.0          1751           0.177743
25   0.09 -0.460000     -83.636360   4674.0          1222           0.174813
26   0.06 -0.340000     -85.000000   4076.0          1583           0.171883
27   0.04 -0.290000     -87.878790   2068.0          1050           0.168954
28   0.03 -0.240000     -88.888890   1016.0           763           0.169930
29   0.02 -0.180000     -90.000000   1004.0          1332           0.167977
30   0.02 -0.140000     -93.333330    614.0          2452           0.175789
31   0.02 -0.100000     -90.909096   5019.0          4284           0.181649
32   0.02 -0.070000     -87.500000   1457.0          1467           0.187508
33   0.02 -0.050000     -71.428570   1987.0          2385           0.195321
34   0.01 -0.030000     -75.000000    125.0          1598           0.187508
35   0.01 -0.030000     -75.000000     44.0           961           0.191414
36   0.01 -0.020000     -66.666670    113.0          1418           0.199227
37   0.01 -0.020000     -66.666670     56.0           430           0.203133
38   0.01  0.010000     100.000000     24.0          2156           0.210945
39   0.01  0.000000       0.000000    517.0          1733           0.214852
40   0.01  0.000000       0.000000    799.0          1723           0.222664
41   0.01 -0.010000     -50.000000    765.0          1568           0.226570
42   0.01 -0.010000     -50.000000    701.0           674           0.234383
43   0.01 -0.010000     -50.000000   3030.0           559           0.238289
44   0.01  0.000000       0.000000   1618.0           501           0.246101
45   0.01 -0.010000     -50.000000      4.0           236           0.250007
46   0.01  0.000000       0.000000      2.0           132           0.257820
47   0.01  0.000000       0.000000    150.0           180           0.261726
48   0.01  0.000000       0.000000      2.0           239           0.269539
49   0.01 -0.010000     -50.000000     18.0           313           0.273445
50   0.01  0.000000       0.000000    439.0           751           0.281257
51   0.01  0.000000       0.000000   2758.0           918           0.285163
52   0.01  0.020000     200.000000      3.0           575           0.312507
53   0.01  0.000000       0.000000    154.0           227           0.343757
54   0.01 -0.010000     -50.000000    259.0           308           0.367194
55   0.01  0.000000       0.000000      1.0           133           0.394537
56   0.01  0.000000       0.000000     30.0           900           0.421881
57   0.01  0.000000       0.000000      NaN             2           0.445318
58   0.01  0.000000       0.000000      NaN             1           0.562504

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
5         True      REGULAR      USD
6         True      REGULAR      USD
7         True      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26       False      REGULAR      USD
27       False      REGULAR      USD
28       False      REGULAR      USD
29       False      REGULAR      USD
30       False      REGULAR      USD
31       False      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34       False      REGULAR      USD
35       False      REGULAR      USD
36       False      REGULAR      USD
37       False      REGULAR      USD
38       False      REGULAR      USD
39       False      REGULAR      USD
40       False      REGULAR      USD
41       False      REGULAR      USD
42       False      REGULAR      USD
43       False      REGULAR      USD
44       False      REGULAR      USD
45       False      REGULAR      USD
46       False      REGULAR      USD
47       False      REGULAR      USD
48       False      REGULAR      USD
49       False      REGULAR      USD
50       False      REGULAR      USD
51       False      REGULAR      USD
52       False      REGULAR      USD
53       False      REGULAR      USD
54       False      REGULAR      USD
55       False      REGULAR      USD
56       False      REGULAR      USD
57       False      REGULAR      USD
58       False      REGULAR      USD  , puts=        contractSymbol             lastTradeDate  strike  lastPrice    bid
0   SPY250311P00500000 2025-03-07 21:06:17+00:00   500.0       0.02   0.01  \
1   SPY250311P00510000 2025-03-07 19:41:38+00:00   510.0       0.03   0.02
2   SPY250311P00515000 2025-03-07 19:05:14+00:00   515.0       0.02   0.02
3   SPY250311P00520000 2025-03-07 20:49:46+00:00   520.0       0.04   0.03
4   SPY250311P00525000 2025-03-07 21:04:27+00:00   525.0       0.03   0.03
..                 ...                       ...     ...        ...    ...
56  SPY250311P00613000 2025-03-06 15:02:33+00:00   613.0      38.20  36.72
57  SPY250311P00614000 2025-03-07 20:51:56+00:00   614.0      38.75  37.72
58  SPY250311P00615000 2025-02-27 15:38:18+00:00   615.0      20.22  38.72
59  SPY250311P00616000 2025-02-27 15:38:18+00:00   616.0      21.19  39.72
60  SPY250311P00620000 2025-02-25 15:19:15+00:00   620.0      27.77  43.72

      ask     change  percentChange  volume  openInterest  impliedVolatility
0    0.02  -0.030000     -60.000004   734.0          1239           0.539067  \
1    0.03  -0.050000     -62.500000  2404.0          1209           0.503911
2    0.03  -0.080000     -79.999990   150.0           284           0.468755
3    0.04  -0.050000     -55.555557   109.0          1070           0.445318
4    0.04  -0.080000     -72.727270   144.0          1063           0.408209
..    ...        ...            ...     ...           ...                ...
56  37.95   0.200001       0.526318     1.0             0           0.478765
57  38.94  13.280001      52.139780     2.0             1           0.486822
58  39.95   0.000000       0.000000     NaN             0           0.497564
59  40.95   0.000000       0.000000     NaN             0           0.506841
60  44.94   0.000000       0.000000     NaN             0           0.542241

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
..         ...          ...      ...
56        True      REGULAR      USD
57        True      REGULAR      USD
58        True      REGULAR      USD
59        True      REGULAR      USD
60        True      REGULAR      USD

[61 rows x 14 columns], underlying={'language': 'en-US', 'region': 'US', 'quoteType': 'ETF', 'typeDisp': 'ETF', 'quoteSourceName': 'Delayed Quote', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'longName': 'SPDR S&P 500 ETF Trust', 'regularMarketPrice': 575.92, 'marketState': 'CLOSED', 'currency': 'USD', 'exchange': 'PCX', 'messageBoardId': 'finmb_6160262', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'corporateActions': [], 'postMarketTime': 1741395592, 'shortName': 'SPDR S&P 500', 'regularMarketTime': 1741381200, 'regularMarketChangePercent': 0.560486, 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 728317800000, 'priceHint': 2, 'postMarketChangePercent': -0.18579097, 'postMarketPrice': 574.85, 'postMarketChange': -1.0700073, 'regularMarketChange': 3.20996, 'regularMarketDayHigh': 577.39, 'regularMarketDayRange': '565.63 - 577.39', 'regularMarketDayLow': 565.63, 'regularMarketVolume': 76139972, 'regularMarketPreviousClose': 572.71, 'bid': 574.65, 'ask': 574.9, 'bidSize': 8, 'askSize': 9, 'fullExchangeName': 'NYSEArca', 'financialCurrency': 'USD', 'regularMarketOpen': 570.9, 'averageDailyVolume3Month': 53336327, 'averageDailyVolume10Day': 73153180, 'fiftyTwoWeekLowChange': 82.06, 'fiftyTwoWeekLowChangePercent': 0.16616045, 'fiftyTwoWeekRange': '493.86 - 613.23', 'fiftyTwoWeekHighChange': -37.309998, 'fiftyTwoWeekHighChangePercent': -0.06084177, 'fiftyTwoWeekLow': 493.86, 'fiftyTwoWeekHigh': 613.23, 'fiftyTwoWeekChangePercent': 12.6427765, 'trailingAnnualDividendRate': 5.662, 'trailingPE': 25.521145, 'trailingAnnualDividendYield': 0.00988633, 'dividendYield': 1.19, 'ytdReturn': 1.43002, 'trailingThreeMonthReturns': -0.99021, 'trailingThreeMonthNavReturns': -0.99021, 'netAssets': 634082230000.0, 'epsTrailingTwelveMonths': 22.566385, 'sharesOutstanding': 917782016, 'bookValue': 429.22, 'fiftyDayAverage': 596.3728, 'fiftyDayAverageChange': -20.45282, 'fiftyDayAverageChangePercent': -0.03429536, 'twoHundredDayAverage': 571.98004, 'twoHundredDayAverageChange': 3.9399414, 'twoHundredDayAverageChangePercent': 0.00688825, 'netExpenseRatio': 0.0945, 'marketCap': 528569008128, 'priceToBook': 1.3417827, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'tradeable': False, 'cryptoTradeable': False, 'symbol': 'SPY'})

In [13]:
# Filter calls for strike above 390
df7 = options.calls[options.calls['strike']>390]

# Check the filtered output
df7.iloc[:,:7]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change
0,SPY250311C00560000,2025-03-07 20:45:41+00:00,560.0,18.00,16.47,16.61,2.100000
1,SPY250311C00565000,2025-03-07 21:06:26+00:00,565.0,11.83,12.20,12.32,-0.420000
2,SPY250311C00570000,2025-03-07 21:14:26+00:00,570.0,8.32,8.42,8.50,-0.980001
3,SPY250311C00571000,2025-03-07 21:14:24+00:00,571.0,7.59,7.73,7.81,-1.059999
4,SPY250311C00572000,2025-03-07 21:14:27+00:00,572.0,7.00,7.07,7.14,-1.060000
5,SPY250311C00573000,2025-03-07 21:14:29+00:00,573.0,6.38,6.44,6.50,-1.270000
6,SPY250311C00574000,2025-03-07 21:09:33+00:00,574.0,5.88,5.84,5.89,-1.050000
7,SPY250311C00575000,2025-03-07 21:14:33+00:00,575.0,5.21,5.26,5.31,-1.220000
8,SPY250311C00576000,2025-03-07 21:14:49+00:00,576.0,4.71,4.71,4.76,-1.230000
9,SPY250311C00578000,2025-03-07 21:14:40+00:00,578.0,3.68,3.70,3.75,-1.330000
10,SPY250311C00579000,2025-03-07 21:14:41+00:00,579.0,3.23,3.25,3.29,-1.330000
11,SPY250311C00580000,2025-03-07 21:14:53+00:00,580.0,2.85,2.83,2.86,-1.280000
12,SPY250311C00581000,2025-03-07 21:14:36+00:00,581.0,2.40,2.43,2.47,-1.320000
13,SPY250311C00582000,2025-03-07 21:14:59+00:00,582.0,2.10,2.07,2.10,-1.290000
14,SPY250311C00583000,2025-03-07 21:14:46+00:00,583.0,1.74,1.74,1.78,-1.290000
15,SPY250311C00584000,2025-03-07 21:14:24+00:00,584.0,1.40,1.45,1.48,-1.130000
16,SPY250311C00585000,2025-03-07 21:14:57+00:00,585.0,1.20,1.18,1.21,-1.210000
17,SPY250311C00586000,2025-03-07 21:14:49+00:00,586.0,0.95,0.95,0.98,-1.160000
18,SPY250311C00587000,2025-03-07 21:13:39+00:00,587.0,0.75,0.75,0.77,-1.110000
19,SPY250311C00588000,2025-03-07 21:14:42+00:00,588.0,0.57,0.58,0.60,-1.050000
20,SPY250311C00589000,2025-03-07 21:14:47+00:00,589.0,0.45,0.44,0.46,-0.930000
21,SPY250311C00590000,2025-03-07 21:14:54+00:00,590.0,0.33,0.32,0.33,-0.850000
22,SPY250311C00591000,2025-03-07 21:14:58+00:00,591.0,0.25,0.24,0.25,-0.750000
23,SPY250311C00592000,2025-03-07 21:14:55+00:00,592.0,0.18,0.17,0.18,-0.620000
24,SPY250311C00593000,2025-03-07 21:14:38+00:00,593.0,0.12,0.12,0.13,-0.550000
25,SPY250311C00594000,2025-03-07 21:13:42+00:00,594.0,0.09,0.08,0.09,-0.460000
26,SPY250311C00595000,2025-03-07 21:12:05+00:00,595.0,0.06,0.05,0.06,-0.340000
27,SPY250311C00596000,2025-03-07 21:05:26+00:00,596.0,0.04,0.03,0.04,-0.290000
28,SPY250311C00597000,2025-03-07 21:00:23+00:00,597.0,0.03,0.02,0.03,-0.240000
29,SPY250311C00598000,2025-03-07 21:12:16+00:00,598.0,0.02,0.01,0.02,-0.180000
30,SPY250311C00599000,2025-03-07 21:11:24+00:00,599.0,0.01,0.01,0.02,-0.140000
31,SPY250311C00600000,2025-03-07 21:11:14+00:00,600.0,0.01,0.01,0.02,-0.100000
32,SPY250311C00601000,2025-03-07 21:02:42+00:00,601.0,0.01,0.01,0.02,-0.070000
33,SPY250311C00602000,2025-03-07 21:10:51+00:00,602.0,0.02,0.01,0.02,-0.050000
34,SPY250311C00603000,2025-03-07 21:13:04+00:00,603.0,0.01,0.00,0.01,-0.030000
35,SPY250311C00604000,2025-03-07 20:40:09+00:00,604.0,0.01,0.00,0.01,-0.030000
36,SPY250311C00605000,2025-03-07 19:58:31+00:00,605.0,0.01,0.00,0.01,-0.020000
37,SPY250311C00606000,2025-03-07 15:13:22+00:00,606.0,0.01,0.00,0.01,-0.020000
38,SPY250311C00607000,2025-03-07 19:45:44+00:00,607.0,0.02,0.00,0.01,0.010000
39,SPY250311C00608000,2025-03-07 19:05:18+00:00,608.0,0.02,0.00,0.01,0.000000
40,SPY250311C00609000,2025-03-07 17:21:10+00:00,609.0,0.01,0.00,0.01,0.000000
41,SPY250311C00610000,2025-03-07 19:40:19+00:00,610.0,0.01,0.00,0.01,-0.010000
42,SPY250311C00611000,2025-03-07 18:51:14+00:00,611.0,0.01,0.00,0.01,-0.010000
43,SPY250311C00612000,2025-03-07 19:53:59+00:00,612.0,0.01,0.00,0.01,-0.010000
44,SPY250311C00613000,2025-03-07 20:09:53+00:00,613.0,0.01,0.00,0.01,0.000000
45,SPY250311C00614000,2025-03-07 19:58:56+00:00,614.0,0.01,0.00,0.01,-0.010000
46,SPY250311C00615000,2025-03-07 19:58:56+00:00,615.0,0.01,0.00,0.01,0.000000
47,SPY250311C00616000,2025-03-06 18:39:08+00:00,616.0,0.01,0.00,0.01,0.000000
48,SPY250311C00617000,2025-03-05 21:04:01+00:00,617.0,0.01,0.00,0.01,0.000000
49,SPY250311C00618000,2025-03-07 18:10:59+00:00,618.0,0.01,0.00,0.01,-0.010000
50,SPY250311C00619000,2025-03-07 18:08:17+00:00,619.0,0.01,0.00,0.01,0.000000
51,SPY250311C00620000,2025-03-07 18:11:46+00:00,620.0,0.01,0.00,0.01,0.000000
52,SPY250311C00625000,2025-03-06 18:59:01+00:00,625.0,0.03,0.00,0.01,0.020000
53,SPY250311C00630000,2025-03-07 17:42:20+00:00,630.0,0.01,0.00,0.01,0.000000
54,SPY250311C00635000,2025-03-07 17:34:21+00:00,635.0,0.01,0.00,0.01,-0.010000
55,SPY250311C00640000,2025-03-05 17:53:14+00:00,640.0,0.01,0.00,0.01,0.000000
56,SPY250311C00645000,2025-03-05 17:00:27+00:00,645.0,0.02,0.00,0.01,0.000000
57,SPY250311C00650000,2025-02-26 15:49:26+00:00,650.0,0.02,0.00,0.01,0.000000
58,SPY250311C00680000,2025-02-26 15:20:12+00:00,680.0,0.01,0.00,0.01,0.000000

## Retrieving Hypertext Markup Language (HTML)

We'll now retrieve India's benchmark index NIFTY50 Index data from Wikipedia.

In [14]:
# Read data from wikipedia
nifty50 = pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1].Symbol.to_list()

# Read five symbols
nifty50[:50]

['ADANIENT',
 'ADANIPORTS',
 'APOLLOHOSP',
 'ASIANPAINT',
 'AXISBANK',
 'BAJAJ-AUTO',
 'BAJFINANCE',
 'BAJAJFINSV',
 'BEL',
 'BPCL',
 'BHARTIARTL',
 'BRITANNIA',
 'CIPLA',
 'COALINDIA',
 'DRREDDY',
 'EICHERMOT',
 'GRASIM',
 'HCLTECH',
 'HDFCBANK',
 'HDFCLIFE',
 'HEROMOTOCO',
 'HINDALCO',
 'HINDUNILVR',
 'ICICIBANK',
 'INDUSINDBK',
 'INFY',
 'ITC',
 'JSWSTEEL',
 'KOTAKBANK',
 'LT',
 'M&M',
 'MARUTI',
 'NESTLEIND',
 'NTPC',
 'ONGC',
 'POWERGRID',
 'RELIANCE',
 'SBILIFE',
 'SHRIRAMFIN',
 'SBIN',
 'SUNPHARMA',
 'TCS',
 'TATACONSUM',
 'TATAMOTORS',
 'TATASTEEL',
 'TECHM',
 'TITAN',
 'TRENT',
 'ULTRACEMCO',
 'WIPRO']

## Retrieving JSON requests

We'll now retrieve json requests from the web and manipualte it using pandas.

```
import requests
from src.creds import *

# Read json request from the alphavantage
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey={av_apikey}'
r = requests.get(url)
data = r.json()

# Manipulate into dataframe
df9 = pd.DataFrame.from_records(data['Time Series (5min)']).T

# Verify the top five rows
df9.head()
```

# Data Storage

## Storing OHLCV data in Excel File

In [15]:
# Dataframe to Excel
from pandas import ExcelWriter

In [16]:
# Storing the fetched data in a separate sheet for each security
writer = ExcelWriter('stocks.xlsx')

# df.to_excel() - this is list comprehension
[pd.DataFrame(ohlcv[symbol].tz_localize(None)).to_excel(writer, symbol) for symbol in dow_stocks]

writer.close()

## Storing OHLCV data in a CSV File

In [17]:
# Save ohlcv data for each securities in stockname.csv format
[pd.DataFrame(ohlcv[symbol]).to_csv(''+symbol+'.csv') for symbol in dow_stocks]
print('*** file saved ***')

*** file saved ***

## Storing Nifty50 data in SQLite Database

In [18]:
# Import & create database 
import sqlalchemy
engine = sqlalchemy.create_engine('sqlite:///India')

In [19]:
# fetch the data from yahoo
data = [yf.download(symbol+'.NS', period='1y', progress=False).reset_index() for symbol in nifty50] 

# save it to database
for frame, symbol in zip(data, nifty50):
    frame.to_sql(symbol, engine, if_exists='replace', index=False)

# Data Loading

## Excel / CSV

In [20]:
# Reading the fetched data in a spreadsheet
gs = pd.read_excel('stocks.xlsx', sheet_name='GS', index_col=0, parse_dates=True)

# Display the last five rows of the data frame to check the results
gs.tail()

                          Close        High         Low        Open   Volume
Price
2025-03-03 00:00:00   605.26001  628.780029  598.320007  622.400024  3152300
2025-03-04 00:00:00  581.140015         600  567.570007   595.97998  4061000
2025-03-05 00:00:00  593.070007  597.119995  576.780029  582.090027  2600600
2025-03-06 00:00:00  567.669983  586.710022  564.619995  580.590027  4332300
2025-03-07 00:00:00  559.669983  568.169983  544.909973  568.169983  4069600

In [21]:
# Read CSV file  
gs = pd.read_csv('GS.csv', index_col=0, parse_dates=True)

# Display the last five rows of the data frame to check the results
gs.tail()

,Close,High,Low,Open,Volume
Price,,,,,
2025-03-03,605.260009765625,628.780029296875,598.3200073242188,622.4000244140625,3152300
2025-03-04,581.1400146484375,600.0,567.5700073242188,595.97998046875,4061000
2025-03-05,593.0700073242188,597.1199951171875,576.780029296875,582.0900268554688,2600600
2025-03-06,567.6699829101562,586.7100219726562,564.6199951171875,580.5900268554688,4332300
2025-03-07,559.6699829101562,568.1699829101562,544.9099731445312,568.1699829101562,4069600

## SQL

In [24]:
# Query from database
result = pd.read_sql_query('SELECT * FROM  "ADANIENT" WHERE "DATE"> "2023-01-01"', engine)

# Display the results
result.tail()

,"('Date', '')","('Close', 'ADANIENT.NS')","('High', 'ADANIENT.NS')","('Low', 'ADANIENT.NS')","('Open', 'ADANIENT.NS')","('Volume', 'ADANIENT.NS')"
243,2025-03-03 00:00:00.000000,2117.100098,2127.250000,2026.550049,2109.000000,1592611
244,2025-03-04 00:00:00.000000,2144.800049,2154.000000,2080.000000,2085.100098,852978
245,2025-03-05 00:00:00.000000,2245.850098,2258.399902,2148.050049,2153.949951,1370106
246,2025-03-06 00:00:00.000000,2252.850098,2268.899902,2226.149902,2260.000000,890270
247,2025-03-07 00:00:00.000000,2247.500000,2267.649902,2227.000000,2249.949951,818806

# Data Manipulation

In [25]:
# Load csv file, specify dayfirst
data = pd.read_csv('spy.csv', index_col=0, parse_dates=True, dayfirst=True)['2011':'2021']
data['Change'] = 100.*np.log(data['Adj Close']).diff().fillna(0)

In [26]:
# subset selection
data.filter(['Open', 'Close']).head()

                  Open       Close
Date
2011-01-03  126.709999  127.050003
2011-01-04  127.330002  126.980003
2011-01-05  126.580002  127.639999
2011-01-06  127.690002  127.389999
2011-01-07  127.559998  127.139999

In [27]:
# drop columns
data.drop('Volume', axis=1).head()

,Open,High,Low,Close,Adj Close,Change
Date,,,,,,
2011-01-03,126.709999,127.599998,125.699997,127.050003,105.443665,0.000000
2011-01-04,127.330002,127.370003,126.190002,126.980003,105.385559,-0.055121
2011-01-05,126.580002,127.720001,126.459999,127.639999,105.933296,0.518400
2011-01-06,127.690002,127.830002,127.010002,127.389999,105.725830,-0.196038
2011-01-07,127.559998,127.769997,126.150002,127.139999,105.518341,-0.196445

In [28]:
# drop rows
data.drop(data.index[-1], axis=0).tail()

,Open,High,Low,Close,Adj Close,Volume,Change
Date,,,,,,,
2020-04-22,278.350006,281.000000,276.910004,279.100006,279.100006,93524600,2.195183
2020-04-23,280.489990,283.940002,278.750000,279.079987,279.079987,104709700,-0.007173
2020-04-24,280.730011,283.700012,278.500000,282.970001,282.970001,85166000,1.384246
2020-04-27,285.119995,288.269989,284.619995,287.049988,287.049988,77896600,1.431548
2020-04-28,291.019989,291.399994,285.399994,285.730011,285.730011,105270000,-0.460903

## Resampling data

In [29]:
# https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
# Resampling to derive weekly values from daily time series
df_weekly = df4[['GS']].resample('W').last()

# Display the last five rows of the data frame to check the output
df_weekly.tail()

Ticker              GS
Date
2025-02-09  652.663696
2025-02-16  657.290710
2025-02-23  622.513123
2025-03-02  622.289978
2025-03-09  559.669983

In [30]:
# Resampling to a specific day of the week: Thu
df_weekly_thu = df4[['GS']].resample('W-THU').last()

# Display the last five rows of the data frame to check the output
df_weekly_thu.tail()

Ticker              GS
Date
2025-02-13  645.747986
2025-02-20  639.091003
2025-02-27  605.000000
2025-03-06  567.669983
2025-03-13  559.669983

In [31]:
# Resampling to derive monthly values from daily time series
df_monthly = df4[['GS']].resample('M').last()

# Display the last five rows of the data frame to check the output
df_monthly.tail()

Ticker              GS
Date
2025-01-31  637.240173
2025-02-28  622.289978
2025-03-31  559.669983

In [32]:
# Create a copy of spy dataframe & reset index
df = data.copy()
df.reset_index(inplace=True)

# Assign separate columns for month & year 
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

# Verify the output
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume,Change,Year,Month
2341,2020-04-23,280.489990,283.940002,278.750000,279.079987,279.079987,104709700,-0.007173,2020,4
2342,2020-04-24,280.730011,283.700012,278.500000,282.970001,282.970001,85166000,1.384246,2020,4
2343,2020-04-27,285.119995,288.269989,284.619995,287.049988,287.049988,77896600,1.431548,2020,4
2344,2020-04-28,291.019989,291.399994,285.399994,285.730011,285.730011,105270000,-0.460903,2020,4
2345,2020-04-29,291.529999,294.880005,290.410004,293.209991,293.209991,118745600,2.584170,2020,4

## Min-Max Index

We'll now use idxmax and idxmin to select the index value that corresponds to the maximum or minimum of the index's percentage change for each year.

In [33]:
# Grouping dataframe to get the max and min values
max_min = {'Change': ['idxmax', 'idxmin']}
df.groupby(['Year']).agg(max_min).T

Year           2011  2012  2013  2014  2015  2016  2017  2018  2019  2020
Change idxmax   151   376   502   997  1169  1276  1549  2008  2014  2320
       idxmin   150   356   619   775  1167  1378  1603  1784  2160  2314

In [34]:
# Check the results for year 2020
df.loc[[2314, 2320]]

,Date,Open,High,Low,Close,Adj Close,Volume,Change,Year,Month
2314,2020-03-16,241.179993,256.899994,237.360001,239.850006,238.447861,297240000,-11.588651,2020,3
2320,2020-03-24,234.419998,244.100006,233.800003,243.149994,243.149994,235494500,8.673099,2020,3

In [35]:
# Check the year wise maximum values
df.loc[df.groupby('Year')['Change'].idxmax()]

,Date,Open,High,Low,Close,Adj Close,Volume,Change,Year,Month
151,2011-08-09,114.070000,117.639999,110.269997,117.480003,98.410210,717828700,4.545085,2011,8
376,2012-06-29,135.199997,136.270004,134.850006,136.100006,116.429924,212250900,2.462113,2012,6
502,2013-01-02,145.110001,146.149994,144.729996,146.059998,126.508362,192059000,2.530732,2013,1
997,2014-12-18,204.740005,212.970001,203.919998,206.779999,185.264771,257633900,2.442778,2014,12
1169,2015-08-26,192.080002,194.789993,188.369995,194.460007,176.826218,339257000,3.767491,2015,8
1276,2016-01-29,190.020004,193.880005,189.880005,193.720001,178.122925,210529300,2.408504,2016,1
1549,2017-03-01,238.389999,240.320007,238.369995,239.779999,225.208954,149158200,1.390048,2017,3
2008,2018-12-26,235.970001,246.179993,233.759995,246.179993,240.192596,218485400,4.928991,2018,12
2014,2019-01-04,247.589996,253.110001,247.169998,252.389999,246.251556,142628800,3.294686,2019,1
2320,2020-03-24,234.419998,244.100006,233.800003,243.149994,243.149994,235494500,8.673099,2020,3

In [36]:
# Assign a new dataframe with pivoted values
newdf = pd.pivot_table(df,
                       index='Month',
                       columns='Year',
                       values='Change',
                       aggfunc=np.sum)

# Analysing year wise statistics for Nasdaq returns
newdf

Year,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Month,,,,,,,,,,
1,1.274784,4.533136,4.992305,-3.588473,-3.007705,-5.106875,1.773661,5.482797,7.702185,-0.040389
2,3.414754,4.248981,1.267803,4.451037,5.468188,-0.082632,3.853910,-3.703775,3.190132,-8.247524
3,0.011998,3.165745,3.726805,0.826168,-1.583016,6.510019,0.124926,-2.779308,1.793888,-13.338431
4,2.855019,-0.669807,1.903029,0.692748,0.978560,0.393356,0.987726,0.515485,4.003994,12.889892
5,-1.127797,-6.193473,2.333515,2.294073,1.277444,1.686869,1.401414,2.401825,-6.589541,NaN
6,-1.701373,3.977941,-1.343450,2.043497,-2.052125,0.346964,0.635470,0.573456,6.727210,NaN
7,-2.020734,1.175972,5.038632,-1.352872,2.233782,3.582183,2.034585,3.637674,1.500635,NaN
8,-5.654439,2.474413,-3.045153,3.870440,-6.288668,0.119692,0.291349,3.142087,-1.688510,NaN
9,-7.194807,2.503478,3.115593,-1.389190,-2.584711,0.005795,1.994914,0.592783,1.927090,NaN
10,10.359135,-1.836561,4.526635,2.327743,8.163496,-1.748908,2.329048,-7.160778,2.186400,NaN
11,-0.407198,0.564365,2.920717,2.710161,0.364831,3.617617,3.010823,1.837927,3.555840,NaN
12,1.039410,0.889483,2.559633,-0.253985,-1.743334,2.006900,1.205499,-9.216842,2.864133,NaN

In [37]:
# Summary statistics
newdf.describe()

Year,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,4.000000
mean,0.070729,1.236139,2.333005,1.052612,0.102229,0.944248,1.636944,-0.389722,2.264455,-2.184113
std,4.491635,3.062620,2.447942,2.365709,3.921519,2.921839,1.101624,4.463040,3.696918,11.445595
min,-7.194807,-6.193473,-3.045153,-3.588473,-6.288668,-5.106875,0.124926,-9.216842,-6.589541,-13.338431
25%,-1.781213,0.255822,1.744223,-0.528706,-2.185271,-0.016312,0.899662,-3.010425,1.720574,-9.520251
50%,-0.197600,1.825193,2.740175,1.434833,-0.609092,0.370160,1.587538,0.583120,2.525266,-4.143957
75%,1.669843,3.368794,3.926763,2.423347,1.516529,2.400721,2.108201,2.586890,3.667879,3.192181
max,10.359135,4.533136,5.038632,4.451037,8.163496,6.510019,3.853910,5.482797,7.702185,12.889892

# Interactive Visualization of Time Series

We use `cufflinks` for interactive visualization. It is one of the most feature rich third-party wrapper around `Plotly` by Santos Jorge. It binds the power of `plotly` with the flexibility of `pandas` for easy plotting.

When you import cufflinks library, all pandas data frames and series objects have a new method `.iplot()` attached to them which is similar to pandas' built-in `.plot()` method.

## Plotting Line Chart

Next, we'll plot the time series data in the line format.

In [38]:
cf.set_config_file(theme='pearl')

In [42]:
df2[['Close']].tail(30).iplot(
    layout=dict(
        title='Line Chart',
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='Close Price'))
    )
)

## Plotting OHLC Data

Next, we'll plot the time series data in ohlc format.

In [44]:
df2.columns = ['_'.join(col) if isinstance(col, tuple) else col for col in df2.columns]
print(df2.columns)
df2[-30:].iplot(
    kind='ohlc',
    title='OHLC Chart',
    layout=dict(
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='Price'))
    )
)

Index(['Close_SPY', 'High_SPY', 'Low_SPY', 'Open_SPY', 'Volume_SPY'], dtype='object')

## Plotting Candlestick

In [45]:
df2[-30:].iplot(
    kind='candle',
    title='Candle Chart',
    layout=dict(
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='Price'))
    )
)

## Plotting Selected Stocks

In [47]:
# Use secondary axis
df4[['GS', 'HD']].iplot(
    layout=dict(
        title='GS vs HD',
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='GS Price'))
    ),
    secondary_y='HD',
    secondary_y_title='HD Price'
)

## Plotting using Subplots

In [49]:
# Use subplots
df4[['GS', 'HD']].iplot(
    subplots=True,
    shape=(2, 1),
    shared_xaxes=True,
    layout=dict(
        title='GS & HD Subplots',
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='Price'))
    )
)

## Normalized Plot

In [51]:
df4.normalize().iplot(
    layout=dict(
        title='Normalized Data',
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='Normalized Value'))
    )
)

## Visualising Return Series

We'll now plot historical daily log normal return series using just one line of code.

In [52]:
# Calculating Log Normal Returns
# Use numpy log function to derive log normal returns
daily_returns = np.log(df4).diff().dropna()

# Display the last five rows of the data frame to check the output
daily_returns.head()

Ticker          AMGN        GS        HD       MCD       UNH
Date
2025-01-03  0.007454  0.008934  0.001852  0.007730  0.016688
2025-01-06 -0.010119  0.005604  0.000488 -0.008859  0.001305
2025-01-07  0.013330 -0.005621 -0.013289 -0.009768  0.001129
2025-01-08  0.008171 -0.000172  0.007700 -0.008469  0.019774
2025-01-10 -0.007522 -0.035126  0.006923 -0.016128 -0.007329

## Plotting Annual Returns

In [54]:
# Plot Mean Annual Returns
(daily_returns.mean() * 252 * 100).iplot(
    kind='bar',
    layout=dict(
        title='Annualized Returns (%)',
        xaxis=dict(title=dict(text='Assets')),
        yaxis=dict(title=dict(text='Annualized Return (%)'))
    )
)

## Plotting Annualized Volatility

In [55]:
# Plot Mean Annualized Volatility
(daily_returns.std() * np.sqrt(252) * 100).iplot(
    kind='bar',
    layout=dict(
        title='Annualized Volatility (%)',
        xaxis=dict(title=dict(text='Assets')),
        yaxis=dict(title=dict(text='Annualized Volatility (%)'))
    )
)

## Plotting Rolling Returns

In [56]:
# To calculate 5 days rolling returns, simply sum daily returns for 5 days as log returns are additive
rolling_return = daily_returns.rolling(5).sum().dropna()

# Display the last five rows of the data frame to check the output
rolling_return.head()

Ticker          AMGN        GS        HD       MCD       UNH
Date
2025-01-10  0.011313 -0.026381  0.003675 -0.035493  0.031567
2025-01-13  0.033762 -0.030061  0.000000 -0.038559  0.053402
2025-01-14  0.032379 -0.020539  0.008720 -0.036953  0.056890
2025-01-15  0.025915  0.043513  0.055333 -0.024632  0.055173
2025-01-16  0.019564  0.055286  0.055580 -0.025273 -0.026917

In [58]:
# Plot Rolling Returns
rolling_return.iplot(
    title='5-Days Rolling Returns',
    layout=dict(
        xaxis=dict(title=dict(text='Date')),
        yaxis=dict(title=dict(text='Rolling Return (%)'))
    )
)

# Time Series Statistics

Statistics is a branch of mathematics that deals with collecting, interpreting, organization and interpretation of data. The two main categories of statistics are descriptive statistics and inferential statistics.

Descriptive statistics help us to understand the data in a meaningful way and is an important part of data analysis. While inferential statistics allows us to infer trends and derive conclusion from it.

In [59]:
# Analysing the daily returns data
daily_returns.describe().T

,count,mean,std,min,25%,50%,75%,max
Ticker,,,,,,,,
AMGN,43.0,0.005431,0.015813,-0.033128,-0.003414,0.006323,0.012188,0.062987
GS,43.0,-0.000512,0.019819,-0.043772,-0.008231,-0.000077,0.012285,0.058431
HD,43.0,-0.000709,0.014246,-0.023952,-0.013000,0.000122,0.007823,0.033325
MCD,43.0,0.002316,0.012854,-0.020977,-0.006948,0.002554,0.006811,0.046863
UNH,43.0,-0.000514,0.021723,-0.074350,-0.010241,0.001129,0.013677,0.038523

## Log Normal Distribution

A normal distribution is the most common and widely used distribution in statistics. It is popularly referred as a “bell curve” or “Gaussian curve”. Financial time series though random in short term, follows a log normal distribution on a longer time frame.

Now that we have derived the daily log returns, we will plot this return distribution and check whether the stock returns follows log normality.

In [61]:
# Plot log normal distribution of returns
daily_returns.iplot(
    kind='histogram',
    title='Histogram of Daily Returns',
    subplots=True,
    layout=dict(
        xaxis=dict(title=dict(text='Daily Return')),
        yaxis=dict(title=dict(text='Frequency'))
    )
)

## Correlation

Correlation defines the similarity between two random variables. As an example we will check correlation between our Nasdaq listed stocks.

In [62]:
# Plot correlation of returns
daily_returns.corr().iplot(
    kind='heatmap',
    title='Correlation Matrix',
    colorscale='Blues',
    layout=dict(
        xaxis=dict(title=dict(text='Assets')),
        yaxis=dict(title=dict(text='Assets'))
    )
)

## Pairwise Correlation

In [63]:
# Compute pairwise correlation
daily_returns.corrwith(daily_returns['GS'])

Ticker
AMGN   -0.039086
GS      1.000000
HD      0.425325
MCD    -0.132872
UNH    -0.016749
dtype: float64